version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - ENV_FILE=.env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: vocab_db
      POSTGRES_USER: vocab_user
      POSTGRES_PASSWORD: vocab_password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: